# =======================================================
# 1. THIẾT LẬP MẶC ĐỊNH VÀ KHỞI TẠO
# =======================================================
/control/verbose 2
/control/saveHistory
/run/verbose 2

# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1


/random/setSeeds 123456 987654
/detector/setCouplingFile ../data/Gel_RINDEX.txt
/analysis/setFileName Result_Gel.root
# Initialize kernel (Bắt buộc phải gọi trước khi set BeamOn hoặc Seed)
/run/initialize

# =======================================================
# 2. CẤU HÌNH THƯ VIỆN NGUỒN HẠT (CRY)
# =======================================================
/CRY/input returnGammas 0
/CRY/input returnElectrons 0  
/CRY/input returnNeutrons 0   
/CRY/input returnProtons 0    
/CRY/input returnPions 0       
/CRY/input returnKaons 0      

/CRY/input date 8-1-2019
/CRY/input latitude 36.461893
/CRY/input altitude 0
/CRY/input subboxLength 0.15

/CRY/update

# Tắt bớt log trong quá trình chạy để terminal đỡ rối
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/run/beamOn 100