# Cấu hình log đầu ra
/control/verbose 2
/control/saveHistory
/run/verbose 2
/run/numberOfThreads 1

#/detector/setCouplingFile ../data/Air_RINDEX.txt
/detector/setCouplingFile ../data/Gel_RINDEX.txt

/run/initialize

/control/execute vis.mac

/CRY/input returnNeutrons 0
/CRY/input returnProtons 0
/CRY/input returnPions 0
/CRY/input returnKaons 0
/CRY/input returnGammas 0
/CRY/input returnElectrons 0

/CRY/input returnMuons 1

/CRY/input date 8-1-2019
/CRY/input latitude 36.461893
/CRY/input altitude 0


/CRY/input subboxLength 0.15
/CRY/update