# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
/run/numberOfThreads 1

# Tyvek: Inside or Outside of acrylic
/detector/tyvekPosition Inside

# Hodoscope's size (X Y Z)
/detector/scintSize 100 10 100 mm

# SiPM's size (X Y Z)
/detector/sipmSize 25 25 1 mm

/detector/setCouplingFile ../data/Air_RINDEX.txt


/run/initialize

#Output Name : Data_Inside_Gel.root
/analysis/setFileName Data_Inside_Air


#
# Initialize kernel
/run/initialize
#

/CRY/input returnGammas 0
/CRY/input returnElectrons 0  
/CRY/input returnNeutrons 0   
/CRY/input returnProtons 0    
/CRY/input returnPions 0       
/CRY/input returnKaons 0    
/CRY/input returnMuons 1 

/CRY/input date 8-1-2019
/CRY/input latitude 36.461893
/CRY/input altitude 0

/CRY/input subboxLength 0.15
/CRY/update

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/run/beamOn 100